### PR TITLE
Implement Windows builds with Python MapScript

### PR DESCRIPTION
**Pull request by hobu**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by akrherz** [comment]
closes #47 :)

**Review by akrherz — APPROVED** [review]

**Comment by geographika** [comment]
Any idea what additional steps/dependencies would be required to include the 2 MapServer database plugins for [MSSQL](https://mapserver.org/input/vector/mssql.html) and [Oracle](https://mapserver.org/input/vector/oracle.html).

**Comment by hobu** [comment]
@geographika given the discussion at https://github.com/conda-forge/gdal-feedstock/issues/936, it is pretty clear there is no interest in hosting the proprietary plugins in Conda Forge. We could build them and host them on an alternative public conda channel I suppose. 

I guess someone could make a business selling compiled plugins against the Conda Forge builds 😉

**Comment by hobu** [comment]
We could probably get away with providing the plugins but not the SDKs. The issue is they would be hand-jammed in the context of a conda package build, however. I'm not sure how we would manage it as the plugin would need to be compiled against specific mapserver builds.

**Comment by geographika** [comment]
The two plugins would be very handy to have as part of the Conda package without any SDKs. They only get used if a LAYER has a PLUGIN value set, so no risk of breaking anything for non Oracle/MSSQL users.

**Pull request merged**
