### PR TITLE
Implement OSX builds

### PR DESCRIPTION
**Pull request by hobu**
* Python MapScript segfaults but the programs seem to run fine.

### CODE REVIEW

**Comment by hobu** [comment]
looks like we need swig on BUILD_PREFIX too somehow. I don't think this exists yet.

**Comment by hobu** [comment]
yeah, like I said above the Python MapScript import segfaults for me when I run natively on osx-arm64. I'm not sure how to fix that but I didn't need (and I rather hate 😛) MapScript.

**Comment by akrherz** [comment]
> yeah, like I said above the Python MapScript import segfaults for me when I run natively on osx-arm64.

Thanks.  I suspect the mapserver 8.2 updates for python mapscript will fix that.

**Comment by hobu** [comment]
I will also putz around with a windows config for this as well. Again with focus on mostly just the commands.

**Comment by hobu** [comment]
> I will also putz around with a windows config for this as well

Scratch that. Adding the old GNU regex library to Conda Forge is not a yak I want to shave for this. I wonder how realistic it is for MapServer to upgrade away from that given it hasn't been released in 10+ years and is GPL and likely pollutes any Windows builds with GPL restrictions.

**Pull request merged**
