### PR TITLE
Python 3.10 + Cross Compile Builds

### PR DESCRIPTION
**Pull request by akrherz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
*  Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

- ~~Establish mac builds~~
- cross compile mac arm, linux ppc, linux aarch
- enable python3.10

:eyes: CI, could this be green on the first try?

### CODE REVIEW

**Comment by akrherz** [comment]
- osx_64 failed with some linking issue with `_mapscript.so`
- osx_arm64 failed with some `swig` problem

Boggling both issues.

**Comment by hobu** [comment]
@msmitherdc has also offered to be a maintainer here. Can add him to this PR or another one.

**Comment by hobu** [comment]
It would be reasonable to disable OSX builds for now if you wanted to. No one really uses mapserver on osx anyway 😄

**Comment by hobu** [comment]
Stacktrace for OSX failure looks like this

```
  * frame #0: 0x0000000102d9a0e4 libpython3.9.dylib`_PyObject_GC_Alloc + 56
    frame #1: 0x0000000102c4d4e4 libpython3.9.dylib`PyDict_New + 104
    frame #2: 0x0000000101d9e17c _mapscript.so`PyInit__mapscript + 76
    frame #3: 0x000000010019fa0c python`_imp_create_dynamic + 2412
    frame #4: 0x00000001000b427c python`cfunction_vectorcall_FASTCALL + 208
```

this is something with how SWIG 4.0.2 is initializing Python on OSX.

**Comment by akrherz** [comment]
> It would be reasonable to disable OSX builds for now

Giving it one more shot before aborting.

**Comment by akrherz** [comment]
> Alternatively you could just ditch the mapscript part

Now you are causing trouble.  We have to keep this somewhat tied to python! ... Oh my, I see there is a PHP feedstock within conda-forge. Oh dear.

**Comment by akrherz** [comment]
Thanks @hobu for your help here, I have given up and rewritten the git history.  Look good?

**Pull request merged**
